### ISSUE TITLE
CatWISE landing page

### ISSUE THREAD

**Issue by bonimy** [catwise/catwise.github.io#1]
- [x] - CatWISE overview
  - [x] - What is CatWISE? An all-sky catalog based on the combination of WISE 2010 and NEOWISE 2013-16. CatWISE is similar to allWISE in that it includes source brightness, position, and motion. However, because it is based on 4x data quantity spanned over an order of magnitude greater timespan, CatWISE reveals fainter sources and provides far more accurate measurements of their motions. 
  - [x] - What makes it different from WISE and neoWISE.
  - [x] - Provides links for deeper material
- [x] - Link to the catalog.
  - [x] - What information am I getting from the catalog. What areas of research can this catalog be used in, and has it been used before.
- [ ] - How the data was compiled. A brief overview of the software used to create CatWISE. (low priority)
- [x] - Resources we need
  - [x] - A banner image
  - [x] - A possible side image.

**Comment by bonimy** [comment]
I'm going to do a rough draft of the page here in markdown so I know the text and possible images I want to put in the page. Sections in angle brackets (e.g. `<note>`). Are notes or ponderings about what I should put in that section.

# CatWISE Overview

`<One sentence description>`
`<Possibly add major contributor names and publication year>`

## What is CatWISE?

CatWISE is an all-sky catalog based on the combination of catalog sources from WISE 2010 and NEOWISE 2013-16. Similar to allWISE, CatWISE includes for every source its brightness, position, and motion. However, CatWISE reveals fainter sources and provides far more accurate measurements of their motions because it is based on 4x the raw data quantity spanned over a 10x greater timespan.

`<Hyperlinks to other instrument pages>`
`<Perhaps some data comparison graphs>`

## Catalog

The full CatWISE catalog is located at `<link>`. 

### Resources provided by catalog

`<example until I get full resources>`

Parameter | Descripton
--- | ---
ra/dec | Celestial coordinates of source (degrees)
snr[1-4] | Signal-to-Noise Ratio for source for W[1-4] channel

## Software Overview

`<Describe software pipeline and >`.

**Comment by petereisenhardt** [comment]
Thanks Nelson!

Can I meet you this afternoon at IPAC (at say 2 or 2:30) to develop this further?

Peter


On May 5, 2019, at 2:44 PM, Nelson Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to do a rough draft of the page here in markdown so I know the text and possible images I want to put in the page. Sections in angle brackets (e.g. <note>). Are notes or ponderings about what I should put in that section.

CatWISE Overview

<One sentence description>
<Possibly add major contributor names and publication year>

What is CatWISE?

CatWISE is an all-sky catalog based on the combination of catalog sources from WISE 2010 and NEOWISE 2013-16. Similar to allWISE, CatWISE includes for every source its brightness, position, and motion. However, CatWISE reveals fainter sources and provides far more accurate measurements of their motions because it is based on 4x the raw data quantity spanned over a 10x greater timespan.

<Hyperlinks to other instrument pages>
<Perhaps some data comparison graphs>

Catalog

The full CatWISE catalog is located at <link>.

Resources provided by catalog

<example until I get full resources>

Parameter       Descripton
ra/dec  Celestial coordinates of source (degrees)
snr[1-4]        Signal-to-Noise Ratio for source for W[1-4] channel
Software Overview

<Describe software pipeline and >.

**Comment by bonimy** [comment]
@petereisenhardt, I'll come meet with you around 2 to 2:30 then.

**Comment by petereisenhardt** [comment]
/project/cosmo/data/CatWISE
CatWISE Data access URL

http://wise2.ipac.caltech.edu/docs/release/allwise/expsup/index.html
AllWISE Explanatory Supplement

https://portal.nersc.gov/project/cosmo/temp/ameisner/fulldepth_neo3/
unWISE full depth image coadd URL

https://portal.nersc.gov/project/cosmo/temp/ameisner/tr_neo3/
unWISE epoch image coadd URL

https://arxiv.org/abs/1905.99999
CatWISE data Overview paper arxiv link

https://irsa.ipac.caltech.edu/applications/WISETiles/
WISE tile lookup URL

**Comment by petereisenhardt** [comment]
/project/cosmo/data/CatWISE
CatWISE Data access URL

http://wise2.ipac.caltech.edu/docs/release/allwise/expsup/index.html
AllWISE Explanatory Supplement

https://portal.nersc.gov/project/cosmo/temp/ameisner/fulldepth_neo3/
unWISE full depth image coadd URL

https://portal.nersc.gov/project/cosmo/temp/ameisner/tr_neo3/
unWISE epoch image coadd URL

https://arxiv.org/abs/1905.99999
CatWISE data Overview paper arxiv link

https://irsa.ipac.caltech.edu/applications/WISETiles/
WISE tile lookup URL

http://unwise.me
unWISE landing page

**Comment by petereisenhardt** [comment]
[catwiseteam.txt](https://github.com/catwise/catwise.github.io/files/3174145/catwiseteam.txt)

catwiseteam.txt

**Comment by bonimy** [comment]
Closing now that webpage is live.
